# Generated by Django 5.0.1 on 2024-01-26 06:46

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=31)),
                ('photo', models.FileField(upload_to='')),
                ('car_type', models.CharField(max_length=31)),
                ('car_number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('sms_code', models.CharField(max_length=15)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(default='Erkak', max_length=10)),
                ('has_baggage', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.carcategory')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
